import type { Song } from './types'

export const song: Song = {
  id: '100k-kilometros',
  title: '100k Kilometros',
  artist: 'Un Cuento Chino',
  bpm: 165,
  timeSignature: 4,
  sections: [
    {
      name: 'Preparación',
      measuresCount: 4,
      chords: '',
      lyrics: '(silencio)',
    },
    {
      name: 'Intro',
      measuresCount: 8,
      chords: 'F C Dm G',
      lyrics: '(instrumental)',
    },
    {
      name: 'Verso 1 (1/2)',
      measuresCount: 4,
      chords: 'C E Am F Fm',
      lyrics: 'Cien mil kilómetros por hora en el tablero,\nel aire cambia y yo me apago por entero.',
    },
    {
      name: 'Verso 1 (2/2)',
      measuresCount: 4,
      chords: 'C E Am F Fm',
      lyrics: 'Flotando en medio de una nube rosa y fría,\nel mundo es chico y me olvidé la geografía.',
    },
    {
      name: 'Puente (1/2)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Miro una foto de los dos en la pantalla,',
    },
    {
      name: 'Puente (2/2)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'No puedo mantener mi mente callada.',
    },
    {
      name: 'Estribillo (1/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Y extraño a mi novia, qué situación tan obvia,',
    },
    {
      name: 'Estribillo (2/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'los días pesan más que la gravedad.',
    },
    {
      name: 'Estribillo (3/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Extraño a mi novia, me gana la fobia',
    },
    {
      name: 'Estribillo (4/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'de estar tan lejos de la realidad.',
    },
    {
      name: 'Estribillo (5/6)',
      measuresCount: 4,
      chords: 'C G F',
      lyrics: '(Oh-oh, oh-oh) No sé cómo volver.',
    },
    {
      name: 'Estribillo (6/6)',
      measuresCount: 4,
      chords: 'C G C',
      lyrics: '(Oh-oh, oh-oh) Te quiero ver.',
    },
    {
      name: 'Verso 2 (1/2)',
      measuresCount: 4,
      chords: 'C E Am F Fm',
      lyrics: 'Cien mil kilómetros metidos en la ida,\ncomiendo el tiempo como un perro sin comida.',
    },
    {
      name: 'Verso 2 (2/2)',
      measuresCount: 4,
      chords: 'C E Am F Fm',
      lyrics: 'Estoy tan lejos del sillón y de mi vida,\ncon la cabeza a la deriva y confundida.',
    },
    {
      name: 'Puente (1/4)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Ya no me sirven los paisajes de ventana,',
    },
    {
      name: 'Puente (2/4)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'si no te veo al despertar por la mañana.',
    },
    {
      name: 'Puente (3/4)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Solo pretendo aterrizar en nuestro piso,',
    },
    {
      name: 'Puente (4/4)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: "pa' rescatar el paraíso que Dios quiso.",
    },
    {
      name: 'Falso Puente (1/3)',
      measuresCount: 4,
      chords: 'C Em F G Am',
      lyrics: 'Y aunque la altura me juegue una mala pasada,\nen esta nave ya no me importa más nada.',
    },
    {
      name: 'Falso Puente (2/3)',
      measuresCount: 4,
      chords: 'F G',
      lyrics: 'Porque solo pienso en ti, si',
    },
    {
      name: 'Falso Puente (3/3)',
      measuresCount: 4,
      chords: 'F G',
      lyrics: 'solo pienso en ti.',
    },
    {
      name: 'Estribillo (1/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Y extraño a mi novia, qué situación tan obvia,',
    },
    {
      name: 'Estribillo (2/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'los días pesan más que la gravedad.',
    },
    {
      name: 'Estribillo (3/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'Extraño a mi novia, me gana la fobia',
    },
    {
      name: 'Estribillo (4/6)',
      measuresCount: 4,
      chords: 'C E Am G F Fm',
      lyrics: 'de estar tan lejos de la realidad.',
    },
    {
      name: 'Estribillo (5/6)',
      measuresCount: 4,
      chords: 'C G F',
      lyrics: '(Oh-oh, oh-oh) No sé cómo volver.',
    },
    {
      name: 'Estribillo (6/6)',
      measuresCount: 4,
      chords: 'C G C',
      lyrics: '(Oh-oh, oh-oh) Te quiero ver.',
    },
  ],
}