import type { Song } from './types'

export const song: Song = {
  id: '30-anos',
  title: '30 Años',
  artist: 'Conociendo Rusia',
  bpm: 127,
  timeSignature: 4,
  sections: [
    {
      name: 'Preparación',
      measuresCount: 2,
      chords: '',
      lyrics: '(silencio)',
    },
    {
      name: 'Intro',
      measuresCount: 4,
      chords: 'Em',
      lyrics: '(instrumental)',
    },
    {
      name: 'Verso 1 (1/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Ya tengo casi 30 años\nPor la noches no me quiero dormir',
    },
    {
      name: 'Verso 1 (2/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Voy soñando despierto sin pestañar, escribiendo en la cocina',
    },
    {
      name: 'Verso 1 (3/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Aprendí a guardar bien los secretos\nNunca pido lo que no me dan',
    },
    {
      name: 'Verso 1 (4/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Vos sabes que aparezco sin avisar\nTraje flores de la huerta',
    },
    {
      name: 'Estribillo (1/2)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nEn la calle no hay porque reír',
    },
    {
      name: 'Estribillo (2/2)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nY en la tele pare de sufrir',
    },
    {
      name: 'Interludio',
      measuresCount: 4,
      chords: 'Em',
      lyrics: '(instrumental)',
    },
    {
      name: 'Verso 2 (1/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Ya volví de donde sople el viento\nAl fin tengo un poco de calor',
    },
    {
      name: 'Verso 2 (2/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Ya mordí la banquina y me levanté\nEncontré agua en el desierto',
    },
    {
      name: 'Verso 2 (3/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Siento la lluvia que cae por el techo\nAlgunos perros que ladran por ahí',
    },
    {
      name: 'Verso 2 (4/4)',
      measuresCount: 4,
      chords: 'Em Bm Em C F#m7 B7 Em',
      lyrics: 'Un recuerdo olvidado de Miramar\nY que nunca se termina',
    },
    {
      name: 'Estribillo (1/2)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nEn la calle no hay porque reír',
    },
    {
      name: 'Estribillo (2/2)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nY en la tele pare de sufrir',
    },
    {
      name: 'Puente (1/4)',
      measuresCount: 4,
      chords: 'C G Bm Em C D# Bm B7 Em',
      lyrics: 'No me cabe más nada en el pecho',
    },
    {
      name: 'Puente (2/4)',
      measuresCount: 4,
      chords: 'C G Bm Em C D# Bm B7 Em',
      lyrics: 'No me importa lo que diga la gilada',
    },
    {
      name: 'Puente (3/4)',
      measuresCount: 4,
      chords: 'C G Bm Em C D# Bm B7 Em',
      lyrics: 'Y la mirada de todos los demás',
    },
    {
      name: 'Puente (4/4)',
      measuresCount: 2,
      chords: 'C G Bm Em C D# Bm B7 Em',
      lyrics: '',
    },
    {
      name: 'Solo de Guitarra',
      measuresCount: 8,
      chords: 'G Em',
      lyrics: '(instrumental)',
    },
    {
      name: 'Estribillo Final (1/4)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nEn la calle no hay porque reír',
    },
    {
      name: 'Estribillo Final (2/4)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nQue la tele pare de sufrir',
    },
    {
      name: 'Estribillo Final (3/4)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nEn la calle no hay porque reír',
    },
    {
      name: 'Estribillo Final (4/4)',
      measuresCount: 4,
      chords: 'C G B7 Em C G B7 F#m7 Em',
      lyrics: 'Yo estoy esperando\nQue la tele pare de sufrir',
    },
    {
      name: 'Cierre',
      measuresCount: 4,
      chords: 'B7 F#m7 Em B7 Em',
      lyrics: 'En la calle no hay porque reír\nMira la tele pare de sufrir',
    },
    {
      name: 'Outro',
      measuresCount: 4,
      chords: 'Em G',
      lyrics: '(instrumental)',
    },
  ],
}