import type { Song } from './types'

export const song: Song = {
  id: 'como-queman',
  title: 'Como Queman',
  artist: 'Un Cuento Chino',
  bpm: 127,
  timeSignature: 4,
  sections: [
    {
      name: 'Preparación',
      measuresCount: 2,
      chords: '',
      lyrics: '(silencio)',
    },
    {
      name: 'Intro',
      measuresCount: 16,
      chords: 'Em G Am B7 (x4) / Em Am B7 Em',
      lyrics: '(instrumental)',
    },
    {
      name: 'Verso 1 (1/4)',
      measuresCount: 4,
      chords: 'Em Am',
      lyrics: 'Vuelvo a cruzar por el callejón,\ncon el recuerdo en el corazón.',
    },
    {
      name: 'Verso 1 (2/4)',
      measuresCount: 4,
      chords: 'B7 Em',
      lyrics: 'El eco lento de tu caminar,\ntodavía sabe cómo regresar.',
    },
    {
      name: 'Verso 1 (3/4)',
      measuresCount: 4,
      chords: 'Em Am',
      lyrics: 'Las viejas letras que te canté,\nsiguen marcadas sobre mi piel,',
    },
    {
      name: 'Verso 1 (4/4)',
      measuresCount: 4,
      chords: 'D G B7',
      lyrics: 'como ese nombre en el cristal\nque la tormenta no va a borrar.',
    },
    {
      name: 'Pre-Coro (1/2)',
      measuresCount: 4,
      chords: 'C Em',
      lyrics: 'Y aunque juro que ya me fui,\nsiempre termino volviendo aquí.',
    },
    {
      name: 'Pre-Coro (2/2)',
      measuresCount: 4,
      chords: 'Am B7',
      lyrics: 'Donde tu nombre se me quedó,\ndonde mi alma se perdió.',
    },
    {
      name: 'Coro (1/4)',
      measuresCount: 4,
      chords: 'Em Am',
      lyrics: '¡Y vuelvo a recorrer, vuelvo a recorrer!\nEsos pasajes que me hacen volver.',
    },
    {
      name: 'Coro (2/4)',
      measuresCount: 4,
      chords: 'D G B7',
      lyrics: 'A la melodía de tu dulce voz,\nal dolor amargo de nuestro adiós.',
    },
    {
      name: 'Coro (3/4)',
      measuresCount: 4,
      chords: 'C B7',
      lyrics: 'Esas letras que un día te canté,\nesas letras que tanto lloré...',
    },
    {
      name: 'Coro (4/4)',
      measuresCount: 4,
      chords: 'Em G Am B7',
      lyrics: '¡Ay, cómo queman hoy!\n¡Ay, cómo queman hoy!',
    },
    {
      name: 'Verso 2 (1/4)',
      measuresCount: 4,
      chords: 'Em Am D',
      lyrics: 'Quedó tu taza sobre el balcón,\ngris y vacía, sin tu ilusión.',
    },
    {
      name: 'Verso 2 (2/4)',
      measuresCount: 4,
      chords: 'G B7',
      lyrics: 'Dejaste el eco de tu reír,\ny desde entonces no sé vivir.',
    },
    {
      name: 'Verso 2 (3/4)',
      measuresCount: 4,
      chords: 'Em Am D',
      lyrics: 'Miro los vidrios, tiembla el cristal,\nmientras la tarde empieza a bajar.',
    },
    {
      name: 'Verso 2 (4/4)',
      measuresCount: 4,
      chords: 'G B7',
      lyrics: 'En cada esquina de la ciudad,\nsolo me responde tu soledad.',
    },
    {
      name: 'Pre-Coro (1/2)',
      measuresCount: 4,
      chords: 'C Em',
      lyrics: 'Y aunque juro que ya me fui,\nsiempre termino volviendo aquí.',
    },
    {
      name: 'Pre-Coro (2/2)',
      measuresCount: 4,
      chords: 'Am B7',
      lyrics: 'Donde tu nombre se me quedó,\ndonde mi alma se perdió.',
    },
    {
      name: 'Coro (1/4)',
      measuresCount: 4,
      chords: 'Em Am',
      lyrics: '¡Y vuelvo a recorrer, vuelvo a recorrer!\nEsos pasajes que me hacen volver.',
    },
    {
      name: 'Coro (2/4)',
      measuresCount: 4,
      chords: 'D G B7',
      lyrics: 'A la melodía de tu dulce voz,\nal dolor amargo de nuestro adiós.',
    },
    {
      name: 'Coro (3/4)',
      measuresCount: 4,
      chords: 'C B7',
      lyrics: 'Esas letras que un día te canté,\nesas letras que tanto lloré...',
    },
    {
      name: 'Coro (4/4)',
      measuresCount: 4,
      chords: 'Em G Am B7',
      lyrics: '¡Ay, cómo queman hoy!\n¡Ay, cómo queman hoy!',
    },
    {
      name: 'Solo Trompeta y Guitarra Eléctrica',
      measuresCount: 16,
      chords: 'Em Am C D Em B7 / Em G Am B7 (x4)',
      lyrics: '(instrumental)',
    },
    {
      name: 'Coro Final (1/5)',
      measuresCount: 4,
      chords: 'Em Am',
      lyrics: '¡Y vuelvo a recorrer, vuelvo a recorrer!\nEsos pasajes que me hacen volver.',
    },
    {
      name: 'Coro Final (2/5)',
      measuresCount: 4,
      chords: 'D G B7',
      lyrics: 'A la melodía de tu dulce voz,\nal dolor amargo de nuestro adiós.',
    },
    {
      name: 'Coro Final (3/5)',
      measuresCount: 4,
      chords: 'C B7',
      lyrics: 'Esas letras que un día te canté,\nesas letras que tanto lloré...',
    },
    {
      name: 'Coro Final (4/5)',
      measuresCount: 4,
      chords: 'Em G Am B7',
      lyrics: '¡Ay, cómo queman hoy!\n¡Ay, cómo queman hoy!',
    },
    {
      name: 'Coro Final (5/5)',
      measuresCount: 3,
      chords: 'Em G Am B7',
      lyrics: '¡Ay, cómo queman hoy!\n¡Ay, cómo queman hoy!',
    },
  ],
}