import type { Song } from './types'

export const song: Song = {
  id: 'cuchillo-guantanamera',
  title: 'Cuchillo Guantanamera',
  artist: 'Airbag',
  bpm: 128,
  timeSignature: 4,
  sections: [
    {
      name: 'Preparación',
      measuresCount: 2,
      chords: '',
      lyrics: '(silencio)',
    },
    {
      name: 'Intro',
      measuresCount: 12,
      chords: 'Am (riff)  F C E Am  F C G G7 (sostenido)',
      lyrics: '(instrumental)',
    },
    {
      name: 'Verso 1 (1/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Tengo el presentimiento de que algo va a pasar',
    },
    {
      name: 'Verso 1 (2/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'La niebla esta cubriendo toda, toda la ciudad',
    },
    {
      name: 'Verso 1 (3/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'He tomado precauciones por si está acá',
    },
    {
      name: 'Verso 1 (4/4)',
      measuresCount: 4,
      chords: 'F C E E7',
      lyrics: 'No me asusta nada, nada mas',
    },
    {
      name: 'Estribillo (1/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Siento que esta vez viene por mi\nY me ataca en la oscuridad',
    },
    {
      name: 'Estribillo (2/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Oh no quiero mas saber de mi\nEl futuro prende mi ansiedad',
    },
    {
      name: 'Estribillo (3/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Pero poco a poco te vencí\nA cuchillos en la oscuridad',
    },
    {
      name: 'Estribillo (4/4)',
      measuresCount: 4,
      chords: 'F C G G7',
      lyrics: 'Oh no quiero mas saber de mi',
    },
    {
      name: 'Verso 2 (1/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Las cartas esta noche solas se repartirán',
    },
    {
      name: 'Verso 2 (2/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Y nuestro destino en sus manos quedara',
    },
    {
      name: 'Verso 2 (3/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Hay secreteos escondidos en la luna de hoy',
    },
    {
      name: 'Verso 2 (4/4)',
      measuresCount: 4,
      chords: 'F C E E7',
      lyrics: 'El pasado guarda tu dolor',
    },
    {
      name: 'Estribillo (1/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Siento que esta vez viene por mi\nY me ataca en la oscuridad',
    },
    {
      name: 'Estribillo (2/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Oh no quiero mas saber de mi\nEl futuro prende mi ansiedad',
    },
    {
      name: 'Estribillo (3/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Pero poco a poco te vencí\nA cuchillos en la oscuridad',
    },
    {
      name: 'Estribillo (4/4)',
      measuresCount: 4,
      chords: 'F C G G7',
      lyrics: 'Oh no quiero mas saber de mi',
    },
    {
      name: 'Solo de Guitarra',
      measuresCount: 16,
      chords: 'F C E Am (x4)',
      lyrics: '(instrumental)',
    },
    {
      name: 'Estribillo Final (1/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Siento que esta vez viene por mi\nY me ataca en la oscuridad',
    },
    {
      name: 'Estribillo Final (2/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Oh no quiero mas saber de mi\nEl futuro prende mi ansiedad',
    },
    {
      name: 'Estribillo Final (3/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Pero poco a poco te vencí\nA cuchillos en la oscuridad',
    },
    {
      name: 'Estribillo Final (4/4)',
      measuresCount: 4,
      chords: 'F C E Am',
      lyrics: 'Oh no quiero mas saber de mi\nA cuchillos en la oscuridad',
    },
    {
      name: 'Final',
      measuresCount: 10,
      chords: 'F C E Am  F C G G7  Am (calderón)',
      lyrics: '(instrumental)',
    },
  ],
}